version:  "3.7"

services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
    depends_on:
      - users
      - app

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    # volumes:
    #   - './services/users:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_DEV_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - PROD_SECRET_KEY=PROD_KEY
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
  app:
    build:
      context: ./services/app/
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    volumes:
      - './services/app/:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 80
    depends_on:
      - users
