version:  "3.7"

services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    ports:
      - 80:80

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    # volumes:
    #   - './services/users:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_DEV_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
